services:
  server:
    build: ./server
    ports:
      - 5050:5000
    command: npm run dev
    volumes:
      - ./server/src:/app/src
    networks:
      - my_network

  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
    networks:
      - my_network

  client:
    build: ./client
    ports:
      - 8080:5173
    command: npm run dev
    depends_on:
      - server
    volumes:
      - ./client/src:/app/src
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
